### PR TITLE
Support Terraform 1.0

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##

This PR moves this skeleton from Terraform 0.14 to 1.0.

## 💭 Motivation and context ##

This is the last step in our journey of migrating Terraform to a current 1.0.x version. We previously upgraded from Terraform 0.12 to 0.13 with #57 and from 0.13 to 0.14 with #62.

This PR is a part of cisagov/cool-system#219 and related to cisagov/setup-env-github-action#41.

This PR is similar to cisagov/skeleton-packer#89 and cisagov/skeleton-ansible-role-with-test-user#29.

When all testing has been completed with Terraform 1.0 and cisagov/setup-env-github-action#41 has been merged, https://github.com/cisagov/skeleton-tf-module/commit/fd95721232ba242516a4c5c2508ac360cf016c93 will be reverted in a new pull request.

## 🧪 Testing ##

To test this PR, I installed Terraform 1.0.7 on my local system and validated the following:
* [x] All pre-commit tests pass locally (note that I had to re-run `terraform init` in both the main and the `examples/basic_usage` directories)
* [x] All GitHub actions pass for this PR
* [x] I was able to successfully `terraform apply` in `examples/basic_usage` without any errors
* [x] I was able to successfully `terraform destroy` all of the resources deployed in the previous step without any errors

## ✅ Checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
Is the deletion of the default provider in `providers.tf` required by v1.0?

**Comment by dav3r** [comment]
> Is the deletion of the default provider in `providers.tf` required by v1.0?

It's not required- see the comment in https://github.com/cisagov/skeleton-tf-module/pull/64/commits/e4a0760a8eeabcccc1d12a3ce2baefd2790a15f3 for more info and let me know if you think of a reason why we shouldn't do this.

**Comment by jsf9k** [comment]
> > Is the deletion of the default provider in `providers.tf` required by v1.0?
> 
> It's not required- see the comment in [e4a0760](https://github.com/cisagov/skeleton-tf-module/commit/e4a0760a8eeabcccc1d12a3ce2baefd2790a15f3) for more info and let me know if you think of a reason why we shouldn't do this.

I have always hated those empty provider blocks, so I am glad to see them go.

**Review by mcdonnnj — APPROVED** [review]
Excellent!

**Pull request merged**
